services:
  postgres:
    image: postgres:15
    container_name: logdb_postgres
    restart: always
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123!
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_wal_size=8GB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "checkpoint_timeout=15min"
      - "-c"
      - "checkpoint_completion_target=0.9"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d logdb" ]
      interval: 2s
      timeout: 3s
      retries: 10


  ingest:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: admin
      PGPASSWORD: admin123!
      PGDATABASE: logdb
    volumes:
      - ./input-logfiles:/input-logfiles:ro
      - ./parsed:/parsed
    command: >
      bash -c '
        ts() { date "+%Y-%m-%d %H:%M:%S.%3N"; }
        echo "$(ts) | Ingest step deployment: START." &&
        ./wait_for_postgres.sh &&
        python csv_parser.py &&
        echo "$(ts) | DEBUG: CSV done" &&
        python copy_loader.py &&
        echo "$(ts) | Ingest step deployment: END."
      '
 

  django:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      ingest:
        condition: service_completed_successfully
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: admin
      PGPASSWORD: admin123!
      PGDATABASE: logdb
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      bash -c '
        ts() { date "+%Y-%m-%d %H:%M:%S.%3N"; }

        echo "$(ts) | Starting migrations…" &&
        python manage.py migrate &&
        echo "$(ts) | Starting Django server…" &&
        python manage.py runserver 0.0.0.0:8000
      '

volumes:
  pgdata:
