version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: logdb_postgres
    restart: always
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123!
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d logdb" ]
      interval: 2s
      timeout: 3s
      retries: 10

  ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: admin
      PGPASSWORD: admin123!
      PGDATABASE: logdb
    volumes:
      - ./input-logfiles:/input-logfiles:ro
      - ./parsed:/parsed
    command: >
      bash -c "
        echo 'DEBUG: Starting entrypoint...' &&
        ls -l /app &&
        ./wait_for_postgres.sh &&
        echo 'DEBUG: Postgres ready' &&
        python parse_to_csv.py &&
        echo 'DEBUG: CSV done' &&
        python load_with_copy.py &&
        echo 'DEBUG: DONE'
      "
  
  

  django:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      ingest:
        condition: service_completed_successfully
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: admin
      PGPASSWORD: admin123!
      PGDATABASE: logdb
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  pgdata:
